//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Shop_Creator_Optimalized
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int ID_Product { get; set; }
        public double Price1 { get; set; }
        public Nullable<double> Shipping_Price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
