//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Shop_Creator_Optimalized
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Price = new HashSet<Price>();
            this.StockStatus = new HashSet<StockStatus>();
            this.Category = new HashSet<Category>();
            this.Opinion = new HashSet<Opinion>();
            this.Opinion1 = new HashSet<Opinion>();
        }
    
        public int ID_Product { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Depth { get; set; }
        public int Producent_ID { get; set; }
        public string Producent_Name { get; set; }
        public string Warranty { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ID_Opinion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Price { get; set; }
        public virtual Price Price2 { get; set; }
        public virtual Promotion Promotion2 { get; set; }
        public virtual StockStatus StockStatus2 { get; set; }
        public virtual ICollection <Promotion> Promotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockStatus> StockStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinion1 { get; set; }
        public virtual Opinion Opinion11 { get; set; }
    }
}
